-- 메인 테이블만 생성: subtitles와 summary
-- 기존 테이블 삭제하고 실제 운영 스키마로 재생성

-- 기존 테이블 삭제 (존재하면)
DROP TABLE IF EXISTS video_summaries CASCADE;

-- 1. subtitles 테이블 (자막 캐시) - 메인 테이블
CREATE TABLE IF NOT EXISTS subtitles (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    youtube_url TEXT NOT NULL,
    lang TEXT NOT NULL DEFAULT 'ko',
    subtitle TEXT NOT NULL
);

-- 2. summary 테이블 (사용자별 요약) - 메인 테이블  
CREATE TABLE IF NOT EXISTS summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    youtube_url TEXT NOT NULL,
    lang TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID NOT NULL REFERENCES auth.users(id),
    title VARCHAR,
    summary VARCHAR
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_subtitles_youtube_url ON subtitles (youtube_url);
CREATE INDEX IF NOT EXISTS idx_subtitles_created_at ON subtitles (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_summary_youtube_url ON summary (youtube_url);
CREATE INDEX IF NOT EXISTS idx_summary_created_at ON summary (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_summary_user_id ON summary (user_id);

-- RLS 정책 설정
ALTER TABLE subtitles ENABLE ROW LEVEL SECURITY;
ALTER TABLE summary ENABLE ROW LEVEL SECURITY;

-- subtitles 정책 (모든 인증된 사용자가 읽기/쓰기 가능)
CREATE POLICY "Allow all operations on subtitles" ON subtitles FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow service role full access to subtitles" ON subtitles FOR ALL TO service_role USING (true);

-- summary 정책 (사용자별 접근 제어)
CREATE POLICY "Users can read their own summaries" ON summary FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own summaries" ON summary FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own summaries" ON summary FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Service role full access to summary" ON summary FOR ALL TO service_role USING (true);

-- 테이블 코멘트
COMMENT ON TABLE subtitles IS 'Cache table for YouTube video subtitles';
COMMENT ON COLUMN subtitles.youtube_url IS 'Normalized YouTube URL';
COMMENT ON COLUMN subtitles.lang IS 'Language code (ko, en, etc.)';
COMMENT ON COLUMN subtitles.subtitle IS 'Extracted subtitle content as text';

COMMENT ON TABLE summary IS 'User-specific video summaries';